print("Hello, VS Code!")
print("    /|")
print("   / |")
print("  /  |")
print(" /___|")
print("If you want to know whether a particular application, ")
print("or a library with particular functionality, is available")
print(" in Python there are a number of possible sources of information.") 
print("The Python web site provides a Python Package Index (also known as the Cheese Shop,") 
print("a reference to the Monty Python script of that name). There is also a search page for")
print("a number of sources of Python-related information. Failing that, just Google for a phrase")
print("including the word ''python'' and you may well get the result you need. If all else fails,")
print("ask on the python newsgroup and there's a good chance someone will put you on the right track.")