print("Hello, VS Code!")
print("    /|")
print("   / |")
print("  /  |")
print(" /___|")
nameting="Freedom"
print("If you want to know whether a particular application, ")
print("or a library with particular functionality, is available")
print(f" in {nameting} there are a number of possible sources of information.") 
print(f"The {nameting} web site provides a {nameting} Package Index also known as the Cheese Shop,") 
print(f"a reference to the Monty {nameting} script of that name). There is also a search page for")
print(f"a number of sources of {nameting}-related information. Failing that, just Google for a phrase")
print(f"including the word {nameting} and you may well get the result you need. If all else fails,")
print(f"ask on the {nameting} newsgroup and there's a good chance someone will put you on the right track.")